tags:
  3D: 3d
  ArcGIS: esri
  atlas: atlas
  base de données: database
  Bash: code
  Blender: blender
  cartographie: carte
  Centipede: satellite
  CNIG: institution
  collecte: telephone
  collecte terrain: telephone
  conférence: conference
  coulisses: masques
  cURL: code
  D3.js: js
  DuckDB: database
  Easter eggs: oeuf
  Esri: esri
  ETL: roue
  ExtJS: js
  Facebook: facebook
  FIG: conference
  FME: roue
  FOSS4G: conference
  GDAL: gdal
  GéoDataDays: conference
  GeoGames: manette
  GeoKettle: roue
  GeoParquet: parquet
  GEOS: globe
  Geotribu: tente
  géo-lecture: atlas
  Git: git
  GitHub: git
  GitLab: git
  Google: google
  Google Earth: google
  Google Maps: google
  Google Street View: google
  GraphHopper: route
  GRASS: grass
  Halloween: citrouille
  HTML: html
  HTML5: html
  IA: cerveau
  IGN: institution
  Input: telephone
  INSPIRE: ananas
  IRC: commentaires
  JavaScript: js
  jeu: manette
  jeux vidéo: manette
  Leaflet: feuille
  Lego: brick
  LIDAR: satellite
  livre: atlas
  Linux: pingouin
  Mapillary: streetview
  MapLibre: maplibre
  Markdown: markdown
  Mastodon: mastodon
  Matrix: commentaires
  Minecraft: manette
  modèle numérique d'élévation: terrain
  MySQL: database
  NoSQL: database
  ODK: telephone
  OGR: gdal
  Open Data Kit: telephone
  OpenDroneMap: drone
  OpenPathView: streetview
  OpenRouteService: route
  open data: open
  open source: opensource
  OpenStreetMap: geoloupe
  Ordnance Survey: institution
  OSRM: route
  Open Earth View: streetview
  Parquet: parquet
  pgDay: database
  pgRouting: route
  PGSession: database
  PostGIS: database
  PostgreSQL: database
  projection: meridiens
  PyCSW: python
  PyGEOS: python
  PyQGIS: python
  PyQt: python
  PySQL: python
  Python: python
  PyWPS: python
  QField: telephone
  QGIS: qgis
  R: rstats
  raster: raster
  relief: terrain
  réseaux sociaux: rezosocio
  route: route
  routing: route
  SAGA: gemeaux
  SQL: database
  three.js: js
  topologie: vector
  Twitter: twitter
  Ubuntu: ubuntu
  Wikipédia: wikipedia
  Windows: windows
