rss:
  cache_dir: !ENV [MKDOCS_PLUGIN_RSS_CACHE_DIR, .cache/plugins/rss]
  categories:
    - categories
    - tags
  comments_path: "#__comments"
  date_from_meta:
    as_creation: date
    default_time: "09:09"
  enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, true]
  image: theme/assets/images/geotribu/background_geotribu.png
  length: 50
  match_path: posts/.*
  pretty_print: false
  url_parameters:
    utm_source: "rss-feed"
    utm_medium: "RSS"
    utm_campaign: "feed-syndication"
